### ISSUE TITLE
Crash with CM11

### ISSUE THREAD

**Issue by juanmreyesa** [domi007/silentSMS#4]
Hello,
I'm cm11 user in my Nexus 4
I install the signed apk, it open but crash when I try to send the SMS.
Is compatible with Android 4.4.4?
Thanks

**Comment by domi007** [comment]
I will update my test device (HTC One S) and see how it goes. Probably during the weekend I'll have time for this.

**Comment by juanmreyesa** [comment]
Hello,
Could you update your phone?
Thanks

**Comment by rancidfrog** [comment]
In 4.4.4 it seems sendRawPdu has been removed.
So unless there is a way to package the function within the app it will not work.

There is an xposed module to add the function, but I do not use xposed. 
[ https://github.com/johnzweng/XposedSendRawSMS ]

If you know of another solution that would be great.

As for CM11 see this issue and ask to include in compilation:
[ https://jira.cyanogenmod.org/browse/CYAN-889 ]

**Comment by rancidfrog** [comment]
Just tested installing xPosed framework and sendrawsms module but with no luck.

SilentSms crashed.

```
09-21 12:06:12.464 I/PackageParser(2337): net.tomcsanyi.domonkos.silentsms: compat added android.permission.WRITE_EXTERNAL_STORAGE android.permission.READ_PHONE_STATE
09-21 12:06:12.479 W/PackageManager(2337): Permission group android.permission-group.MESSAGES from package net.tomcsanyi.domonkos.silentsms ignored: original from android
09-21 12:06:54.339 I/ActivityManager(2337): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=net.tomcsanyi.domonkos.silentsms/.SilentSMS bnds=[400,640][400,640]} from pid 3409
09-21 12:06:54.564 I/dalvikvm(2586): Could not find method com.android.internal.telephony.Phone.getIccSmsInterfaceManager, referenced from method net.tomcsanyi.domonkos.silentsms.SilentSMS.sendSMS
09-21 12:06:54.914 I/ActivityManager(2337): Displayed net.tomcsanyi.domonkos.silentsms/.SilentSMS: +357ms
09-21 12:07:00.884 D/SilentSMS(2586): Retrieving phone instance ...
09-21 12:07:00.889 D/SilentSMS(2586): Retrieving SmsInterfaceManager ...
09-21 12:07:00.889 E/AndroidRuntime(2586):  at net.tomcsanyi.domonkos.silentsms.SilentSMS.sendSMS(SilentSMS.java:187)
09-21 12:07:00.889 E/AndroidRuntime(2586):  at net.tomcsanyi.domonkos.silentsms.SilentSMS.access$2(SilentSMS.java:173)
09-21 12:07:00.889 E/AndroidRuntime(2586):  at net.tomcsanyi.domonkos.silentsms.SilentSMS$2.onClick(SilentSMS.java:97)
09-21 12:07:00.894 W/ActivityManager(2337):   Force finishing activity net.tomcsanyi.domonkos.silentsms/.SilentSMS
09-21 12:07:01.449 W/ActivityManager(2337): Activity pause timeout for ActivityRecord{429c3ad0 u0 net.tomcsanyi.domonkos.silentsms/.SilentSMS t3 f}
09-21 12:07:03.559 I/WindowState(2337): WIN DEATH: Window{42a33058 u0 net.tomcsanyi.domonkos.silentsms/net.tomcsanyi.domonkos.silentsms.SilentSMS}

```

**Comment by domi007** [comment]
All right, I see. The xPosed module uses a totally different way to handle sending rawPDUs, so it won't work with SilentSMS that uses reflection.
I think the best would be if I updated the code to use the xPose module too, maybe adding a button to the UI which could be used to switch between the two implementations.

On the other hand it is totally possible, that the xPosed module needs to be supported from Cyanogenmod too, which I can't control or change.

**Comment by rancidfrog** [comment]
Updating the code with both options would be great.

zerosms has the same problem, see comments on https://github.com/virtualabs/ZeroSMS/commit/202808f89b050a0483b1300b9d96e38f267dbebe,
Maybe he has some ideas, too.

Is there any other way other than using xposed modules?
Recompiling ROM with the changes needed is much more complicated.
Another idea would be "AT Command Injection", which this tool, Android-IMSI-Catcher-Detector, claims to support - see latest release notes, https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/releases
And, [ http://stackoverflow.com/questions/18489717/how-to-send-sms-by-gsm-modem-in-pdu-mode | http://mobiletidings.com/2009/01/12/sending-out-an-sms-in-pdu-mode/ ]

**Comment by Ruchita7** [comment]
The app crashes after trying to send SMS from Nexus 5 emulator as well. 
The error thrown is :  
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.NoSuchMethodError: No interface method getIccSmsInterfaceManager()Lcom/android/internal/telephony/IccSmsInterfaceManager; in class Lcom/android/internal/telephony/Phone; or its super classes (declaration of 'com.android.internal.telephony.Phone' appears in /system/framework/telephony-common.jar)
                                                     at net.tomcsanyi.domonkos.silentsms.SilentSMS.sendSMS(SilentSMS.java:187)
                                                     at net.tomcsanyi.domonkos.silentsms.SilentSMS.access$2(SilentSMS.java:173)
                                                     at net.tomcsanyi.domonkos.silentsms.SilentSMS$2.onClick(SilentSMS.java:97)
                                                     at android.view.View.performClick(View.java:5198)
                                                     at android.view.View$PerformClick.run(View.java:21147)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
